Pr/merge
tocco/tocco-docs pull request #364
Opened 2021-01-11 11:03 UTC by stewue

### Contributor checklist

- [ ] My contribution is **ready to be merged** as is
- [ ] I verified the modifications **render properly**
- [ ] I used **spell checking**
- [ ] I **used the styling and structure aids available** in [Sphinx/ResT](http://www.sphinx-doc.org/en/stable/rest.html). (Links use `` `…`_``, enumerations `#.`, lists `*`, code ``` ``…`` ```/`.. code::`, warnings .. `warning::`, etc.)
- [ ] I reread the text keeping in mind that the text has to be **comprehended** fully **by the target audience**

### Description

2021-02-24 13:32 UTC, michael-spahn requested changes

2021-02-24 13:32 UTC, michael-spahn commented on framework/modules/entityoperation.rst
> +However there is the option to set a relation as privileged. In such a case the relation is moved without checking the permission of the user.
Custom Merge Handler ist auch eine Variante

2021-02-24 13:32 UTC, michael-spahn commented on framework/modules/entityoperation.rst
> +Additional the entity ``Resource`` is always an "all-or-nothing-relation" relation.
Additionally / relation doppelt am schluss

2021-03-17 13:07 UTC, stewue commented on framework/modules/entityoperation.rst
> +If a user has not write access for a relation (or for some related entities) the relation is automatically moved and is not displayed.
To many relations werden immer versucht zu verschieben. Sofern es keinen Speziellen RelationMergeHandler gibt wird einfach der ToManyRelationMergeHandler verwendet.

2021-03-17 14:05 UTC, michael-spahn approved these changes

2021-03-17 14:06 UTC, merged